inc/classes/class-admin.php
templates/backend/paywall/post-preview.php

For https://github.com/laterpay/revenue-generator/issues/40

Gh 40 Adds auto incrementing default title.

---

inc/classes/class-admin.php

GH-16 Hides Setting submenu.

---

inc/classes/class-post-types.php
templates/backend/paywall/post-preview.php

GH-137 Updates drop down label based on post type.

---

templates/backend/contribution/dashboard.php

GH-161 Fixes typo.

---

inc/classes/post-types/class-subscription.php
inc/classes/post-types/class-time-pass.php
uninstall.php

GH-159 Fixes Already bought link.
GH-160 Fixes single article purchase giving access to entire site.

GH-159 GH-160 Fixes single article purchase giving access to entire site. 

---

.distignore
assets/src/js/pages/revenue-generator-contribution.js
assets/src/js/pages/revenue-generator-paywall.js
composer.json
inc/classes/class-plugin.php
package-lock.json
package.json
readme.txt
revenue-generator.php

GH-103 Updated readme and corrected version.

---

inc/classes/class-settings.php

GH-211 Removes UA id from setting defaults

---

inc/classes/class-admin.php

GH-16 Fixes Minor bug and Conflict for verifying merchant credentials

---

.distignore
.github/workflows/deploy.yml

Deploy Action : Added Deploy Action.

---

uninstall.php

GH-11 Updated to delete settings option on uninstall.

---

inc/classes/post-types/class-paywall.php

GH-165 Fixes Paywall priority.

---

composer.json
inc/classes/class-config.php
inc/classes/class-plugin.php
inc/classes/class-settings.php
languages/revenue-generator.po
package-lock.json
package.json
revenue-generator.php

and Updated settings options. for latest GA ID.
related to #219

GH-219 Updated Version to 1.0.1 in code 

---

readme.txt

GH-226 readme update.

---

inc/classes/class-admin.php

related to #18 ticket feedback

GH-18 Fixes Preview issue for excluded category.

---

readme.txt

This PR addresses [CLIENTS-659](https://laterpay.atlassian.net/browse/CLIENTS-659).
- Changes order of tags.
- Removes dash from two-word tags since it's not required.

CLIENTS-659: Update plugin tags

---

inc/classes/post-types/class-paywall.php

GH-18 Fixes issues with multiple categories on excluded paywall

---

inc/classes/class-admin.php
templates/backend/contribution/create.php
templates/backend/contribution/dashboard.php

This PR addresses feedback from [CLIENTS-656](https://laterpay.atlassian.net/browse/CLIENTS-656?focusedCommentId=76548).
- Show different wording of submit button and success message when editing the offer.
- Fixed issue with Contribution offer's title not displaying in Dashboard.

CLIENTS-656: Editable contributions tweaks

---

inc/classes/post-types/class-contribution.php

Ref: [CLIENTS-656](https://laterpay.atlassian.net/browse/CLIENTS-656)

CLIENTS-656: Fix Contributions description not saving

---

inc/classes/class-shortcodes.php
templates/backend/contribution/dashboard.php

GH-247 Fixes contribution shortcode redirecting to 404

---

.github/CODEOWNERS

Updates code owner to laterpay's in-house developer.

Code Owner : Update code owner.

---

assets/src/js/pages/revenue-generator-contribution.js

This fixes code formatting with `npm run format:js` command.

Fixes code formatting

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/feature_request.md

- Update assignees value for issue templates
cc: @milindmore22 @tomasstark

Update assignees value for issue templates

---

tests/phpunit/inc/classes/post-types/test-class-paywall.php
tests/phpunit/inc/classes/test-class-admin.php
tests/phpunit/inc/classes/test-class-frontend-post.php

Tried to cover key function from Paywall and frontend post.

GH-274 Add unit tests for Paywall related code.

---

readme.txt

https://laterpay.atlassian.net/browse/CT-984
I removed all existing tags and replaced them with "Laterpay" to reduce our organic users while we work on the 2.0 migration.

Update Tags in readme.txt
